name: Get Jira issue key from branch name
description: Gets the leading Jira issue key from the branch name (x-y) eg lrfnw-001

inputs:
  prefix:
    description: Jira issue prefix (xxx as in xxx-000)
    required: true

  branch:
    description: A specific branch to search, instead of auto
    required: false

outputs:
  issue-key: 
    description: The issue key
    value: ${{ steps.extract-key.outputs.ISSUE_KEY }}

runs:
  using: composite

  steps:
    # find the appropriate branch name of the pr depending on trigger (pull_request or workflow_dispatch)
    - name: Get branch name
      if: ${{ !inputs.branch }}
      id: branch-name
      uses: tj-actions/branch-names@v6

    # extract the jira issue key from the branch name to use as slot name
    - name: Extract issue key
      id: extract-key
      shell: bash
      run: |
        BRANCH_NAME=${{ steps.branch-name.outputs.current_branch || inputs.branch }}
        PREFIX=${{ inputs.prefix }}
        BRANCH_NAME=${BRANCH_NAME,,}
        PREFIX=${PREFIX,,}
        ISSUE_KEY=$(echo "$BRANCH_NAME" | sed -e "s/\($PREFIX-[0-9]*\)-.*/\1/")
        echo "ISSUE_KEY=${ISSUE_KEY^^}" >> $GITHUB_OUTPUT