
name: Build and push container image to Azure
description: Build and push container image to Azure

inputs:
  registry-name: 
    description: ACR name
    required: true

  registry-password:
    description: ACR password
    required: true

  image-tags:
    description: Image tags
    required: true

runs:
  using: composite

  steps:
    # setup buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # log in to azure acr
    - name: Log in to Azure container registry
      uses: docker/login-action@v1.10.0

      with:
        registry: https://${{ inputs.registry-name }}.azurecr.io/
        username: ${{ inputs.registry-name }}
        password: ${{ inputs.registry-password }}

    # build and push container to acr
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      
      with:
        push: true
        tags: ${{ inputs.image-tags }}
        file: ./Dockerfile