name: Update app version number
description: Update an Azure web app version number in its app settings

inputs:
  image-tags: 
    description: Image tags
    required: true

  resource-group-name: 
    description: Resource group name
    required: true

  app-name:
    description: Web app name
    required: true

  app-setting-name:
    description: App setting name
    required: true

  slot-name:
    description: Slot name
    required: true

  azure-credentials:
    description: Azure service principal credentials
    required: true

runs:
  using: composite

  steps:
    # extract version number, strip the container registry name from the image tag
    - name: Extract version number
      id: extract-version
      shell: bash

      run: |
        tag=$(echo "${{ inputs.image-tags }}" | sed -rn 's/([^:]+):(.+)$/\2/p')
        echo "$tag"

    # log in to azure
    - name: Log in to Azure
      uses: azure/login@v1

      with:
        creds: ${{ inputs.azure-credentials }}

    # update app settings
    - name: Add version number to app settings
      uses: azure/CLI@v1

      with:
        inlineScript: |
            az webapp config appsettings set \
            --resource-group ${{ inputs.resource-group-name }} \
            --name ${{ inputs.app-name }} \
            --slot ${{ inputs.slot-name }} \
            --settings ${{ inputs.app-setting-name }}=${{ steps.extract-version.outputs.tag }} \
            --output none
