name: Build and push container image to Azure
description: Build and push container image to Azure

inputs:
  registry-name: 
    description: ACR name
    required: true

  registry-password:
    description: ACR password
    required: true

  image-tags:
    description: Image tags
    required: true

  build-args:
    description: Dockerfile build args
    required: false

  cache-from:
    description: Cache options to buildx
    required: false

  cache-to:
    description: Cache options to buildx
    required: false

runs:
  using: composite

  steps:
    # setup buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # log in to azure acr
    - name: Log in to Azure container registry
      uses: docker/login-action@v3

      with:
        registry: https://${{ inputs.registry-name }}.azurecr.io/
        username: ${{ inputs.registry-name }}
        password: ${{ inputs.registry-password }}

    # build and push container to acr
    - name: Build and push container image to registry
      uses: docker/build-push-action@v5

      with:
        push: true
        tags: ${{ inputs.image-tags }}
        file: ./Dockerfile
        build-args: ${{ inputs.build-args }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}