# shared workflow to deploy a web app container to an azure app service
# deploys to a deployment slot
name: Deploy an Azure web app image to an app service slot

on:
  workflow_call:
    inputs:
      tags: 
        required: true
        type: string

      app-name:
        required: true
        type: string

      slot-name:
        required: true
        type: string

    secrets:
      publish-profile:
        required: true

jobs:
  deploy:
      name: 🚀
      runs-on: ubuntu-latest

      steps:
        - name: Deploy web app
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2

          with:
            app-name: ${{ inputs.app-name }}
            slot-name: ${{ inputs.slot-name }}
            publish-profile: ${{ secrets.publish-profile }}
            images: ${{ inputs.tags }}