
name: Build and push container to Azure
description: Build and push container to Azure ACR with generated version tags

inputs:
  registry-name: 
    description: ACR name
    required: true

  registry-password:
    description: ACR password
    required: true

  image-name:
    description: Image name
    required: true

outputs:
  tags:
    description: Image name with tags
    value: ${{ steps.export-tags.outputs.tags }}

runs:
  using: composite

  steps:
    # generate image tag based on the latest git commit/tag
    - name: Generate version numbers
      id: generate-version-tags
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry-name }}.azurecr.io/${{ inputs.registry-name }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch,suffix=-{{ sha }}-{{ date 'YYMMDDHHmm' }}
          type=ref,event=pr,suffix=-{{ sha }}-{{ date 'YYMMDDHHmm' }}
          type=semver,pattern={{ version }}-{{ date 'YYMMDDHHmm' }}
        flavor: |
          latest=false

    # output tag versions to caller workflow
    - name: Export version numbers
      id: export-tags
      run: echo "::set-output name=tags::${{ steps.generate-version-tags.outputs.tags }}"
      shell: bash

    # setup buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # log in to azure acr
    - name: Log in to Azure container registry
      uses: docker/login-action@v1.10.0
      with:
        registry: https://${{ inputs.registry-name }}.azurecr.io/
        username: ${{ inputs.registry-name }}
        password: ${{ inputs.registry-password }}

    # build and push container to acr
    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.generate-version-tags.outputs.tags }}
        file: ./Dockerfile